name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build with Gradle
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
         java-version: 1.8
         node-version: '12.x'
    - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - run: npm install
    - run: ./android/scripts/build-apk.sh

    - uses: actions/upload-artifact@v1
      with:
        name: Debug-Release APK
        path: android/app/build/outputs/apk/release/app-release.apk